# Port Server Configuration

ServerHost: localhost
ServerPort: 8000
ServerReload: true
LocalDirectoryBaseStorage: "resources"

# Authentication Configuration

ReceiverUsername: tarazan
ReceiverPassword: 1q2w3e4r
SenderUsername: jane
SenderPassword: q1w2e3r4

